# Site settings
title: Cora Lam
email: coralam17@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Another student at the University of Waterloo avoiding the geese.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://coraellation.github.io/" # the base hostname & protocol for your site
twitter_username: coraellation
github_username:  coraellation
youtube: https://www.youtube.com/c/coralam
linkedin: https://www.linkedin.com/in/coraellation/
instagram: https://www.instagram.com/coraellation/
resume: "/assets/Cora_Lam_Resume_2022.pdf"

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
