# Site settings
title: Cora Lam
email: coralam17@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Another student at the University of Waterloo avoiding the geese.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://coraellation.github.io/" # the base hostname & protocol for your site
twitter_username: coraellation
github_username:  coraellation

# Build settings
markdown: kramdown
